// <auto-generated />
using DotnetReactShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250303064920_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("DotnetReactShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is the first sample product.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Sample Product A",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is the second sample product.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Sample Product B",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "This is the third sample product.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Sample Product C",
                            Price = 19.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
